services:
  app:
    container_name: proselyteapi
    build:
      context: .
    environment:
      DB_CONNECTION_HOST: db
      DB_CONNECTION_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proselyteapi
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379